// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"
	company "golang/golang-study/internal/company"

	mock "github.com/stretchr/testify/mock"
)

// CompanyStore is an autogenerated mock type for the CompanyStore type
type CompanyStore struct {
	mock.Mock
}

// getCompany provides a mock function with given fields: ctx, id
func (_m *CompanyStore) getCompany(ctx context.Context, id string) (company.Company, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for getCompany")
	}

	var r0 company.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (company.Company, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) company.Company); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(company.Company)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCompanyStore creates a new instance of CompanyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyStore {
	mock := &CompanyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
