// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"
	conversation "golang/golang-study/internal/conversation"

	mock "github.com/stretchr/testify/mock"
)

// MessageService is an autogenerated mock type for the MessageService type
type MessageService struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: ctx, message
func (_m *MessageService) CreateMessage(ctx context.Context, message conversation.Message) (conversation.Message, error) {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 conversation.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, conversation.Message) (conversation.Message, error)); ok {
		return rf(ctx, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, conversation.Message) conversation.Message); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Get(0).(conversation.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, conversation.Message) error); ok {
		r1 = rf(ctx, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMessage provides a mock function with given fields: ctx, id
func (_m *MessageService) DeleteMessage(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMessage provides a mock function with given fields: ctx, id
func (_m *MessageService) GetMessage(ctx context.Context, id string) (conversation.Message, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 conversation.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (conversation.Message, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) conversation.Message); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(conversation.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMessage provides a mock function with given fields: ctx, id, updated
func (_m *MessageService) UpdateMessage(ctx context.Context, id string, updated conversation.Message) (conversation.Message, error) {
	ret := _m.Called(ctx, id, updated)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessage")
	}

	var r0 conversation.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, conversation.Message) (conversation.Message, error)); ok {
		return rf(ctx, id, updated)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, conversation.Message) conversation.Message); ok {
		r0 = rf(ctx, id, updated)
	} else {
		r0 = ret.Get(0).(conversation.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, conversation.Message) error); ok {
		r1 = rf(ctx, id, updated)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
